added cleanup of unique md5 tmp file after import, picbatch taxon tablee no longer tracks barcode, image batch resizer now uses temp folder.
calacademy-research/web-asset-importer pull request #41
Opened 2024-05-28 18:23 UTC by delarocamcas

message: added cleanup of unique md5 tmp file after import, picbatch taxon tablee no longer tracks barcode, image batch resizer now uses temp folder.

files added:
image_batch_resizer/run_resizer.sh: script that runs passive image batch resizer and will respawn process if exit != 0 in order to run through rate limits on drive.

files modified:
picturae_importer.py:  only sends uniquely new taxonomic fullname to picbatch, no creates a row for every barcode.

picturae_DDL.sql: removed catalognumeber column from picturaetaxa_added, changed hybrid field to BOOLEAN instead of BIT.

importer.py: added at_exit cleanup function line remove md5 folder path for TMP/ folder after completion of run.

2024-05-28 18:24 UTC, delarocamcas commented on PIC_dbcreate/Picturae_DDL.sql
>                                                  family varchar(512),
added boolean to allow for python style boolean instead of 1/0 bit

2024-05-28 18:32 UTC, delarocamcas commented on image_batch_resizer/img_batch_resizer.py
>                              while img_quality > 20:
now resizes image in /tmp folder and then saves only copies final compressed version in destination file.

2024-05-28 18:33 UTC, delarocamcas commented on image_batch_resizer/run_resizer.sh
.sh file to prevent process from dropping before completion, restarts after 5 minutes if non -0 exit code.

2024-05-28 18:36 UTC, delarocamcas commented on picturae_importer.py
no long need second command to update md5, as now added during initial insert.

2024-05-28 18:37 UTC, delarocamcas commented on picturae_importer.py
making sure only unique taxonomic fullnames get added to the picbatch database.

2024-05-28 18:46 UTC, delarocamcas commented on sql_csv_utils.py
>              df: pandas dataframe, the record table uploaded to the database in question
modifying sql insert to match new state of picbatch db DDL.

2024-05-28 18:47 UTC, delarocamcas commented on string_utils.py
modified string util method string_to_bool to first check if bool. and convert value to lower before converting.

2024-05-28 18:52 UTC, delarocamcas commented on string_utils.py
improved method to check if bool before converting , and convert lowercase value.

2024-05-28 19:03 UTC, delarocamcas commented on string_utils.py
checks if already bool first , and converts value to lower and string to make it easier to convert.

2024-05-28 19:04 UTC, delarocamcas commented on temp_utility_scripts/remove_incomplete_attachments.py
generalist function that can remove a list of internal filepaths from image server , only used if once has an existing list of un-attached filepaths.

2024-05-28 19:05 UTC, delarocamcas commented on tests/botany_importer_test_class.py
initializing dummy self.record_full, to make it compatible with the init_all_vars function.

2024-05-29 16:49 UTC, foozleface requested changes
only the one question but potential impact...

2024-05-29 16:49 UTC, foozleface commented on image_batch_resizer/run_resizer.sh
Why are you running this as an external process? it's native python, that seems... indirect?

2024-05-29 18:56 UTC, delarocamcas commented on image_batch_resizer/img_batch_resizer.py
>      """convert_tiff_folder: creates new folder of resized jpegs from a
updated function notes

2024-05-29 21:27 UTC, foozleface reviewed
your call - see inline comment. Once that's resolved (or not per your own feelings) OK to commit.

2024-05-29 21:27 UTC, foozleface commented on image_batch_resizer/img_batch_resizer.py
this whole funciton is... deep. recommend refactoring now or at a later date. Chatgpt did this, and it's more or less what I"m thinking. Code not checked for validity: 
import os
import shutil
from PIL import Image

def convert_tiff_folder(source_dir, dest_dir, tmp_dir, min_bar, quality, max_size_kb, resize_to=None):
    """Convert TIFF images in a directory to resized JPEGs with specified constraints."""
    for root, dirs, files in os.walk(source_dir):
        if 'undatabased' in dirs:
            process_directory(root, dest_dir, tmp_dir, min_bar, quality, max_size_kb, resize_to)

def process_directory(root, dest_dir, tmp_dir, min_bar, quality, max_size_kb, resize_to):
    tiff_dir = os.path.join(root, 'undatabased')
    output_dir = os.path.join(dest_dir, os.path.basename(root), 'resized_jpg')
    os.makedirs(output_dir, exist_ok=True)
    
    for file_name in os.listdir(tiff_dir):
        if file_name.endswith(".txt"):
            continue
        
        barcode = int(remove_non_numerics(file_name))
        if barcode >= min_bar and "Cover" not in file_name:
            if file_name.lower().endswith(('.tiff', '.tif')):
                process_file(tiff_dir, file_name, output_dir, tmp_dir, quality, max_size_kb, resize_to)

def process_file(tiff_dir, file_name, output_dir, tmp_dir, quality, max_size_kb, resize_to):
    base_name = os.path.splitext(file_name)[0]
    output_file_name = f"{base_name}.jpg"
    output_file_path = os.path.join(output_dir, output_file_name)
    tmp_file_path = os.path.join(tmp_dir, output_file_name)

    if should_skip(output_file_path, max_size_kb):
        print(f"Skipping {file_name}, already processed.")
        return

    file_path = os.path.join(tiff_dir, file_name)
    img_quality = quality

    with Image.open(file_path) as image:
        print(f"resizing file {file_name}")

        if resize_to is not None:
            image = image.resize(resize_to)

        while img_quality > 20:
            image.save(tmp_file_path, 'JPEG', quality=img_quality, optimize=True, subsampling=0)
            current_size_kb = os.path.getsize(tmp_file_path) / 1024

            if current_size_kb <= max_size_kb:
                shutil.copyfile(tmp_file_path, output_file_path)
                os.remove(tmp_file_path)
                print(f"Image {file_name} resized successfully")
                break

            img_quality = adjust_quality(img_quality, current_size_kb, max_size_kb)

        if img_quality <= 20:
            print(f"Warning: Could not reduce {file_name} to under {max_size_kb}KB without dropping below min quality.")

def should_skip(output_file_path, max_size_kb):
    if os.path.exists(output_file_path):
        size = os.path.getsize(output_file_path)
        return size / 1024 <= max_size_kb
    return False

def adjust_quality(img_quality, current_size_kb, max_size_kb):
    if current_size_kb > (max_size_kb + 300):
        return img_quality - 5
    return img_quality - 1

def remove_non_numerics(s):
    return ''.join(filter(str.isdigit, s))

2024-05-30 16:25 UTC, foozleface approved these changes

2024-05-30 16:25 UTC, merged