Picturae import-- added importer build steps, other improvements to jenkins
calacademy-research/web-asset-importer pull request #63
Opened 2024-08-02 00:52 UTC by delarocamcas

2024-08-02 16:26 UTC, foozleface requested changes
The only important changes is the venv in iz_import and pushing the mailing list logic down a level. Other changes at your discretion.

2024-08-02 16:26 UTC, foozleface commented on image_client.py
>              self.monitoring_tools = MonitoringTools(config=config, report_path=config.REPORT_PATH)
you have a conditional at the derived class level around the mailing list (botany importer and ich importer) and another one here - probably should have one or the other? Is there a case where we could get in trouble if we don't check both? Maybe some kind of cleverness around the config file where the image_client.py knows to check a vaiable named $COLLECTION_mailing_list (some variant on that) and we don't need the check in the derived class.

2024-08-02 16:26 UTC, foozleface commented on image_client.py
This whole block (lines 130-170) seem a bit convoluted. Without any thought at all, below  what chatGPT output for that code block, revised. I'm not advocating it (haven't even proofed it) but I think some kind of restructuing is in order.
if (
    "undatabased" in original_path.lower()
    and self.monitoring_tools.path != self.config.ACTIVE_REPORT_PATH
    and self.config.MAILING_LIST
):
    self.monitoring_tools.path = self.config.ACTIVE_REPORT_PATH

if id is None:
    id = "N/A"

if r.status_code != 200:
    self.logger.debug(f"FAIL - return code {r.status_code}. data: {data}")

    if r.status_code == 409:
        self.logger.error(f"Image already in server; skipping for {upload_path}")
        raise DuplicateImageException
    else:
        self.logger.error(f"Image upload aborted: {r.status_code}:{r.text}")

    if self.config.MAILING_LIST:
        self.monitoring_tools.add_imagepath_to_html(
            image_path=original_path,
            id=id,
            success=False,
        )
    raise UploadFailureException

params = {
    # ... other params ...
}

logging.info(f"Uploaded: {local_filename},{attach_loc},{url}")
logging.info("adding to image")

if self.config.MAILING_LIST:
    self.monitoring_tools.add_imagepath_to_html(
        image_path=original_path,
        id=id,
        success=True,
    )

2024-08-02 16:26 UTC, foozleface commented on importer_jenkins.template.sh
Maybe break this up into multiple shell files called by a master one? this is fairly long, and it looks like a bunch of steps. That might make debugging and reading easier. your call.

2024-08-02 16:26 UTC, foozleface commented on iz_import.sh
>      python3 ./client_tools.py -vvvv IZ import >& iz_import_log.txt &
probably need the source venv/bin/activate like the other two?

2024-08-02 16:26 UTC, foozleface commented on picturae_importer.py
Yeah, we have four of these code blocks, If we can push all this logic down a level everything cleans up nicely.

2024-08-02 16:35 UTC, delarocamcas commented on importer_jenkins.template.sh
Sure thing, I can split it into the intitial unittest section, and then the have each importer run in a second .sh script

2024-08-02 16:46 UTC, delarocamcas commented on ichthyology_importer.py
>      def build_filename_map(self, full_path):
full_path=full_path.lower() , some ubuntu systems are case sensitive thus this errored out in the test env. , I removed it and did a test import, but I might want to double check that taking this out doesn't throw a wrench in any functions down the line.

2024-08-05 19:02 UTC, delarocamcas commented on Jenkinsfile
using workspace variable instead of regex

2024-08-05 19:02 UTC, delarocamcas commented on PIC_dbcreate/Picturae_DDL.sql
forgot to add this table in on prior PRs , necessary for notes from nature expedition assembly

2024-08-05 19:03 UTC, delarocamcas commented on image_client.py
> +
initializing monitoring tools with image_client

2024-08-05 19:09 UTC, merged